name: Build Windows exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手动触发按钮

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyqt6

      - name: Build exe
        run: pyinstaller --onefile --noconsole main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: txt2jpg-x64
          path: dist/main.exe
